"""General Tools — body-level split."""
from tool_runtime.general_tools.artifact_tools import handle_artifact_search, handle_artifact_read_content_safe, handle_artifact_save_result, handle_artifact_tag, handle_artifact_delete_soft
from tool_runtime.general_tools.web_tools import handle_web_search, handle_weather_current, handle_weather_forecast, handle_news_search, handle_web_fetch_summary, handle_web_official_doc_search, handle_web_extract_links, handle_web_save_to_artifact
from tool_runtime.general_tools.session_tools import handle_session_list, handle_session_get_summary, handle_session_create, handle_session_archive, handle_run_list_recent, handle_run_get_summary, handle_session_snapshot, handle_session_list_snapshots, handle_session_rewind, handle_session_checkpoint, handle_session_export
from tool_runtime.general_tools.memory_tools import handle_memory_search, handle_memory_create, handle_memory_list, handle_memory_confirm, handle_memory_get_profile, handle_memory_set_profile, handle_memory_update, handle_memory_delete_soft
from tool_runtime.general_tools.skill_tools import handle_skill_list, handle_skill_request_load, handle_skill_load, handle_skill_find, handle_skill_create, handle_skill_inspect
from tool_runtime.general_tools.pdf_tools import handle_pdf_extract_text
from tool_runtime.general_tools.file_tools import handle_file_list, handle_file_exists, handle_file_read, handle_file_edit, handle_file_patch, handle_ws_list_files, handle_ws_read_text_preview, handle_ws_write_artifact_file, handle_ws_path_exists, handle_ws_get_metadata
from tool_runtime.general_tools.command_tools import handle_command_approved_exec, handle_powershell_approved_script, handle_slash_run, handle_python_exec
from tool_runtime.general_tools.agent_tools import handle_agent_spawn, handle_agent_list_roles, handle_agent_team, handle_agent_get_result
from tool_runtime.general_tools.runtime_tools import handle_knowledge_index_artifact, handle_knowledge_reindex, handle_knowledge_search, handle_knowledge_get_source, handle_knowledge_get_chunk_summary, handle_knowledge_explain_not_found, handle_runtime_health, handle_runtime_selfcheck, handle_runtime_diagnostics, handle_runtime_retention_preview, handle_runtime_archive_preview, handle_report_render_markdown, handle_report_save_artifact, handle_doc_render_from_safe_summary, handle_table_render_markdown, handle_diagram_render_mermaid, handle_text_redact, handle_text_diff, handle_text_extract_keywords, handle_text_classify, handle_json_validate, handle_yaml_validate, handle_csv_summarize, handle_table_extract
from tool_runtime.general_tools.shared import ROOT, WS_ROOT, _generate_diff_preview, _workspace_path


def register_all_general_tools(registry):
    from tool_runtime.general_tools.registry import register_all_general_tools as _register
    return _register(registry)
__all__ = [
    'register_all_general_tools',
    'ROOT',
    'WS_ROOT',
    '_generate_diff_preview',
    '_workspace_path',
    'handle_artifact_search',
    'handle_artifact_read_content_safe',
    'handle_artifact_save_result',
    'handle_artifact_tag',
    'handle_artifact_delete_soft',
    'handle_web_search',
    'handle_weather_current',
    'handle_weather_forecast',
    'handle_news_search',
    'handle_web_fetch_summary',
    'handle_web_official_doc_search',
    'handle_web_extract_links',
    'handle_web_save_to_artifact',
    'handle_session_list',
    'handle_session_get_summary',
    'handle_session_create',
    'handle_session_archive',
    'handle_run_list_recent',
    'handle_run_get_summary',
    'handle_session_snapshot',
    'handle_session_list_snapshots',
    'handle_session_rewind',
    'handle_session_checkpoint',
    'handle_session_export',
    'handle_memory_search',
    'handle_memory_create',
    'handle_memory_list',
    'handle_memory_confirm',
    'handle_memory_get_profile',
    'handle_memory_set_profile',
    'handle_memory_update',
    'handle_memory_delete_soft',
    'handle_skill_list',
    'handle_skill_request_load',
    'handle_skill_load',
    'handle_skill_find',
    'handle_skill_create',
    'handle_skill_inspect',
    'handle_pdf_extract_text',
    'handle_file_list',
    'handle_file_exists',
    'handle_file_read',
    'handle_file_edit',
    'handle_file_patch',
    'handle_ws_list_files',
    'handle_ws_read_text_preview',
    'handle_ws_write_artifact_file',
    'handle_ws_path_exists',
    'handle_ws_get_metadata',
    'handle_command_approved_exec',
    'handle_powershell_approved_script',
    'handle_slash_run',
    'handle_python_exec',
    'handle_agent_spawn',
    'handle_agent_list_roles',
    'handle_agent_team',
    'handle_agent_get_result',
    'handle_knowledge_index_artifact',
    'handle_knowledge_reindex',
    'handle_knowledge_search',
    'handle_knowledge_get_source',
    'handle_knowledge_get_chunk_summary',
    'handle_knowledge_explain_not_found',
    'handle_runtime_health',
    'handle_runtime_selfcheck',
    'handle_runtime_diagnostics',
    'handle_runtime_retention_preview',
    'handle_runtime_archive_preview',
    'handle_report_render_markdown',
    'handle_report_save_artifact',
    'handle_doc_render_from_safe_summary',
    'handle_table_render_markdown',
    'handle_diagram_render_mermaid',
    'handle_text_redact',
    'handle_text_diff',
    'handle_text_extract_keywords',
    'handle_text_classify',
    'handle_json_validate',
    'handle_yaml_validate',
    'handle_csv_summarize',
    'handle_table_extract',
]
