"""v3.0 canonical-only tool namespace data.

Each tuple is:

    (
        canonical_tool_id,
        category,
        group,
        action,
        display_name,
        short_label,
        usage_hint,
        not_for,
        handler_id,
    )

Only canonical_tool_id is exposed publicly. handler_id is the internal
implementation key (used by registry.dispatch); it is not part of the
public catalog, LLM prompt, or frontend.
"""

from __future__ import annotations


CATEGORY_DEFS: dict[str, dict[str, str]] = {
    "host": {
        "name": "Host 本机环境",
        "description": "当前运行机器上的本机 OS / Shell / PowerShell / Python 工具。",
    },
    "workspace": {
        "name": "Workspace 工作区",
        "description": "工作区文件、Artifact 制品和 workspace 元数据。",
    },
    "knowledge": {
        "name": "Knowledge 知识库",
        "description": "知识库问答、检索、导入和索引管理。",
    },
    "network": {
        "name": "Network 网络分析",
        "description": "离线网络配置解析、接口 / 路由提取和配置翻译。",
    },
    "web": {
        "name": "Web 外部资料",
        "description": "公开 Web、官方文档、新闻、天气和网页摘要。",
    },
    "runtime": {
        "name": "Runtime 运行审计",
        "description": "运行状态、session、run、review 和审计信息。",
    },
    "memory": {
        "name": "Memory 记忆",
        "description": "记忆搜索、创建、确认、profile 和更新。",
    },
    "report_data": {
        "name": "Report / Data / Text 输出处理",
        "description": "报告、表格、文本、JSON / YAML / CSV 和图表处理。",
    },
    "agent": {
        "name": "Agent 多 Agent",
        "description": "技能、子 Agent、角色、团队和结果读取。",
    },
}


NS_DATA = [
    ("host.shell.exec", "host", "shell", "exec", "本机 Shell 执行", "host.shell.exec",
     "Run a shell command on THIS local machine (NOT a remote device). Opens approval popup. Use for: ip lookup, system info, local diagnostics.",
     "Do not use for network device access. Prefer workspace/network tools for direct workspace-file or config parsing tasks.",
     "host.shell.exec"),
    ("host.powershell.exec", "host", "powershell", "exec", "本机 PowerShell 执行", "host.powershell.exec",
     "Run PowerShell on THIS local machine. Opens approval popup.",
     "Do not use for network device access.",
     "host.powershell.exec"),
    ("host.python.exec", "host", "python", "exec", "本机 Python 执行", "host.python.exec",
     "Run Python on the local host (sandboxed). Use for approved computation, data processing, custom parsing, or tasks that need code.",
     "Do not use for network device access. Prefer specialized workspace/network/knowledge tools when they directly satisfy the task.",
     "host.python.exec"),
    ("host.command.slash_run", "host", "command", "slash_run", "Slash 命令执行", "host.command.slash_run",
     "Run a slash command on the local host.",
     "Do not use for unregistered slash commands.",
     "host.command.slash_run"),
    ("workspace.file.list", "workspace", "file", "list", "列出工作区文件", "workspace.file.list",
     "List workspace files with names and sizes.",
     "Do not cross workspaces or list absolute paths.",
     "workspace.file.list"),
    ("workspace.file.exists", "workspace", "file", "exists", "检查工作区文件是否存在", "workspace.file.exists",
     "Check if a file exists.",
     "Do not use outside the current workspace.",
     "workspace.file.exists"),
    ("workspace.file.read", "workspace", "file", "read", "读取工作区文件", "workspace.file.read",
     "Read a workspace file. MUST be called first before network.config.parse/translate — read the config content, then pass it to parsing tools. Use for: uploaded configs, logs, reports, any text file in workspace.",
     "Do not use for artifacts, knowledge base, or arbitrary absolute paths.",
     ""),
    ("workspace.file.read_image", "workspace", "file", "read_image", "读取图片信息", "workspace.file.read_image",
     "Read image file metadata — dimensions, format, size. Does NOT OCR. Ask user to describe content.",
     "Do not use for text/code files. Not for OCR.",
     ""),
    ("workspace.file.preview", "workspace", "file", "preview", "工作区文本预览", "workspace.file.preview",
     "Preview first lines of a file.",
     "Do not read full large files; use workspace.file.read.",
     ""),
    ("workspace.file.edit", "workspace", "file", "edit", "编辑工作区文件", "workspace.file.edit",
     "Edit a file with string replacement. Requires approval.",
     "Do not use for absolute paths outside the workspace.",
     "workspace.file.edit"),
    ("workspace.file.patch", "workspace", "file", "patch", "工作区文件补丁", "workspace.file.patch",
     "Apply a diff/patch to a file. Requires approval.",
     "Do not use for absolute paths outside the workspace.",
     "workspace.file.patch"),
    ("workspace.file.write_artifact", "workspace", "file", "write_artifact", "写入制品文件", "workspace.file.write_artifact",
     "Write content and register as artifact.",
     "Do not write to arbitrary paths.",
     ""),
    ("workspace.metadata.get", "workspace", "metadata", "get", "读取工作区元数据", "workspace.metadata.get",
     "Get workspace metadata and stats.",
     "Do not return secrets.",
     "workspace.metadata.get"),
    ("workspace.artifact.list", "workspace", "artifact", "list", "列出制品", "workspace.artifact.list",
     "List workspace artifacts.",
     "Do not return artifact bodies; use workspace.artifact.read.",
     "workspace.artifact.list"),
    ("workspace.artifact.read", "workspace", "artifact", "read", "读取制品", "workspace.artifact.read",
     "Read an artifact's content.",
     "Do not use to bypass artifact safety policy.",
     "workspace.artifact.read"),
    ("workspace.artifact.save", "workspace", "artifact", "save", "保存制品", "workspace.artifact.save",
     "Save content as a new artifact.",
     "Do not save secrets; route through review when claiming deployable.",
     "workspace.artifact.save"),
    ("workspace.artifact.diff", "workspace", "artifact", "diff", "制品差异", "workspace.artifact.diff",
     "Diff two artifacts or files.",
     "Do not use for non-artifact files.",
     "workspace.artifact.diff"),
    ("workspace.artifact.export", "workspace", "artifact", "export", "导出制品", "workspace.artifact.export",
     "Export an artifact to external format.",
     "Do not export outside the workspace.",
     "workspace.artifact.export"),
    ("workspace.artifact.search", "workspace", "artifact", "search", "搜索制品", "workspace.artifact.search",
     "Search artifacts by title or type.",
     "Do not return artifact bodies.",
     "workspace.artifact.search"),
    ("workspace.artifact.tag", "workspace", "artifact", "tag", "制品标签", "workspace.artifact.tag",
     "Tag an artifact.",
     "Do not modify artifact body content.",
     "workspace.artifact.tag"),
    ("workspace.artifact.delete_soft", "workspace", "artifact", "delete_soft", "软删除制品", "artifact.delete_soft",
     "Soft-delete an artifact. Requires approval.",
     "Do not perform hard deletion.",
     "workspace.artifact.delete_soft"),
    ("workspace.document.pdf.extract_text", "workspace", "document", "pdf_extract_text", "提取 PDF 文本", "workspace.document.pdf.extract_text",
     "Extract text from a PDF.",
     "Do not use for non-PDF files.",
     "workspace.document.pdf.extract_text"),
    ("knowledge.search", "knowledge", "search", "search", "知识库检索", "knowledge.search",
     "Search the workspace knowledge base for indexed documents and chunks. Use for facts from uploaded files, previous research, or stored configs.",
     "Do not return unredacted full text.",
     "knowledge.search"),
    ("knowledge.chunk.read", "knowledge", "chunk", "read", "读取知识块", "knowledge.chunk.read",
     "Read a knowledge chunk's content by id. Use after knowledge.search to get full details.",
     "Do not return unredacted secrets.",
     ""),
    ("knowledge.chunk.summary", "knowledge", "chunk", "summary", "知识块摘要", "knowledge.chunk.summary",
     "Get a summary of a knowledge chunk.",
     "Do not return the full chunk body when not needed.",
     ""),
    ("knowledge.parent.read", "knowledge", "parent", "read", "读取父文档", "knowledge.parent.read",
     "Read the parent document of a matched chunk.",
     "Do not return unredacted full text.",
     ""),
    ("knowledge.source.read", "knowledge", "source", "read", "读取知识源", "knowledge.source.read",
     "Read the full content of a knowledge source.",
     "Do not return unredacted full content.",
     ""),
    ("knowledge.source.get", "knowledge", "source", "get", "获取知识源元数据", "knowledge.source.get",
     "Get details of a specific knowledge source.",
     "Do not return full content; use knowledge.source.read.",
     ""),
    ("knowledge.source.list", "knowledge", "source", "list", "列出知识源", "knowledge.source.list",
     "List all indexed knowledge sources with status and count.",
     "Do not include full content.",
     ""),
    ("knowledge.chunk.list", "knowledge", "chunk", "list", "列出知识块", "knowledge.chunk.list",
     "List all chunks for a knowledge source.",
     "Do not include full content.",
     ""),
    ("knowledge.import.file", "knowledge", "import", "file", "导入知识文件", "knowledge.import.file",
     "Import an uploaded file into the knowledge base.",
     "Do not import unredacted secrets.",
     ""),
    ("knowledge.import.document", "knowledge", "import", "document", "导入知识文档", "knowledge.import.document",
     "Import a document from URL into the knowledge base.",
     "Do not import unredacted secrets.",
     ""),
    ("knowledge.import.artifact", "knowledge", "import", "artifact", "导入知识制品", "knowledge.import.artifact",
     "Import a workspace artifact into the knowledge base.",
     "Do not import unredacted artifacts.",
     ""),
    ("knowledge.source.reindex", "knowledge", "source", "reindex", "重建索引", "knowledge.source.reindex",
     "Reindex a specific knowledge source.",
     "Do not run against untrusted source without review.",
     ""),
    ("knowledge.source.reindex_all", "knowledge", "source", "reindex_all", "重建全部索引", "knowledge.source.reindex_all",
     "Reindex ALL knowledge sources (destructive, slow).",
     "Do not run in production without explicit approval.",
     ""),
    ("knowledge.source.disable", "knowledge", "source", "disable", "停用知识源", "knowledge.source.disable",
     "Disable a knowledge source from searches.",
     "Do not delete sources.",
     ""),
    ("knowledge.source.delete", "knowledge", "source", "delete", "删除知识源", "knowledge.source.delete",
     "Permanently delete a knowledge source.",
     "Do not delete without explicit confirmation.",
     ""),
    ("knowledge.not_found.explain", "knowledge", "not_found", "explain", "解释未命中", "knowledge.not_found.explain",
     "Explain why a search returned no results.",
     "Use only when a query has no result.",
     ""),
    ("network.config.parse", "network", "config", "parse", "解析网络配置", "network.config.parse",
     "Offline parse a network device config file. Does NOT require real device access — works with uploaded materials.",
     "Do not log into real devices. Do not generate deployable configs.",
     "network.config.parse"),
    ("network.interface.extract", "network", "interface", "extract", "提取接口", "network.interface.extract",
     "Extract interface entries from a config.",
     "Do not log into real devices.",
     "network.interface.extract"),
    ("network.route.extract", "network", "route", "extract", "提取路由", "network.route.extract",
     "Extract route entries from a config.",
     "Do not log into real devices.",
     "network.route.extract"),
    ("network.config.translate", "network", "config", "translate", "翻译网络配置", "network.config.translate",
     "Translate config between vendor formats. Pass filepath for uploaded files or source_config for short inline text. Do NOT call network.config.parse before this — pass filepath or source_config directly.",
     "translated_config is NOT deployable_config.",
     ""),
    ("network.pcap.parse", "network", "pcap", "parse", "解析 PCAP 报文", "network.pcap.parse",
     "Parse a workspace PCAP file, summarize packets, and group bidirectional 5-tuples. Use for pcap/pcapng/报文/抓包 analysis.",
     "Do not use for text configs; use network.config.* for device configuration files.",
     ""),
    ("network.pcap.session", "network", "pcap", "session", "读取 PCAP 会话", "network.pcap.session",
     "Read parsed PCAP session metadata by session_id, including packet count and connection groups.",
     "Do not use before parsing when no session_id is known.",
     ""),
    ("network.pcap.filter", "network", "pcap", "filter", "过滤 PCAP 五元组", "network.pcap.filter",
     "Filter a parsed PCAP session by bidirectional src/sport/dst/dport 5-tuple.",
     "Do not use without a parsed session_id and target flow.",
     ""),
    ("network.pcap.align", "network", "pcap", "align", "TCP 序列对齐", "network.pcap.align",
     "Analyze TCP sequence/ack alignment for retransmission, sequence gaps, SYN/FIN/RST, and anomalies.",
     "Do not use for non-TCP packet questions unless a TCP flow is selected.",
     ""),
    ("web.search", "web", "search", "search", "公开 Web 搜索", "web.search",
     "Search the public web for current facts, news, vendor docs, or information not in workspace. Falls back to web.docs.official_search.",
     "Do not query private / local / login-walled URLs.",
     "web.search"),
    ("web.docs.official_search", "web", "docs", "official_search", "官方文档检索", "web.docs.official_search",
     "Search official vendor documentation and technical references.",
     "Do not query private documentation portals.",
     "web.docs.official_search"),
    ("web.page.summarize", "web", "page", "summarize", "网页摘要", "web.page.summarize",
     "Fetch and summarize a public web page by URL. Use when user provides a URL to analyze.",
     "Do not query private / local / login-walled URLs.",
     "web.page.summarize"),
    ("web.page.extract_links", "web", "page", "extract_links", "提取网页链接", "web.page.extract_links",
     "Extract all links from a web page. Use before web.page.summarize to find specific URLs.",
     "Do not query private / local / login-walled URLs.",
     "web.page.extract_links"),
    ("web.page.save_artifact", "web", "page", "save_artifact", "保存网页到制品", "web.page.save_artifact",
     "Save a web page as a workspace artifact.",
     "Do not save authenticated pages.",
     "web.page.save_artifact"),
    ("web.news.search", "web", "news", "search", "公开新闻搜索", "web.news.search",
     "Search news sources for recent articles on a topic.",
     "Do not query private / local / login-walled URLs.",
     ""),
    ("web.weather.current", "web", "weather", "current", "当前天气", "web.weather.current",
     "Get current weather conditions for a location.",
     "Use only when an explicit weather question is asked.",
     ""),
    ("web.weather.forecast", "web", "weather", "forecast", "天气预报", "web.weather.forecast",
     "Get weather forecast for a location.",
     "Use only when an explicit weather question is asked.",
     ""),
    ("runtime.health", "runtime", "health", "health", "运行健康检查", "runtime.health",
     "Check runtime health — LLM connectivity, tool registry, modules. Use before heavy operations.",
     "Do not include sensitive trace payloads.",
     "runtime.health"),
    ("runtime.diagnostics", "runtime", "health", "diagnostics", "运行诊断", "runtime.diagnostics",
     "Run full diagnostic on agent runtime.",
     "Do not include sensitive trace payloads.",
     "runtime.diagnostics"),
    ("runtime.selfcheck", "runtime", "health", "selfcheck", "运行时自检", "runtime.selfcheck",
     "Run a self-check on all core subsystems.",
     "Do not include sensitive trace payloads.",
     "runtime.selfcheck"),
    ("runtime.retention.preview", "runtime", "retention", "preview", "保留预览", "runtime.retention.preview",
     "Preview retention policy effects.",
     "Do not execute retention without explicit approval.",
     ""),
    ("runtime.archive.preview", "runtime", "archive", "preview", "归档预览", "runtime.archive.preview",
     "Preview data affected by archive operation.",
     "Do not execute archive without explicit approval.",
     ""),
    ("run.list", "runtime", "run", "list", "列出运行", "run.list",
     "List recent agent runs with status and intent.",
     "Do not return full trace bodies.",
     "run.list"),
    ("run.summary.get", "runtime", "run", "summary_get", "运行摘要", "run.summary.get",
     "Get detailed summary of a specific run.",
     "Do not return full trace bodies.",
     "run.summary.get"),
    ("session.list", "runtime", "session", "list", "列出会话", "session.list",
     "List active sessions with metadata.",
     "Do not include sensitive trace payloads.",
     "session.list"),
    ("session.summary.get", "runtime", "session", "summary_get", "会话摘要", "session.summary.get",
     "Get session summary.",
     "Do not include sensitive trace payloads.",
     "session.summary.get"),
    ("session.snapshot.create", "runtime", "session", "snapshot_create", "创建会话快照", "session.snapshot.create",
     "Create session snapshot for audit.",
     "Do not include secrets in snapshots.",
     ""),
    ("session.snapshot.list", "runtime", "session", "snapshot_list", "列出快照", "session.snapshot.list",
     "List session snapshots.",
     "Do not return sensitive payloads.",
     ""),
    ("session.checkpoint", "runtime", "session", "checkpoint", "会话检查点", "session.checkpoint",
     "Create session checkpoint for rewind.",
     "Do not include secrets.",
     "session.checkpoint"),
    ("session.rewind", "runtime", "session", "rewind", "会话回滚", "session.rewind",
     "Rewind session to checkpoint (destructive).",
     "Do not include secrets in rewind steps.",
     "session.rewind"),
    ("session.export", "runtime", "session", "export", "导出会话", "session.export",
     "Export session to JSON/Markdown.",
     "Do not include secrets in exported artifacts.",
     "session.export"),
    ("review.item.list", "runtime", "review", "item_list", "列出评审项", "review.item.list",
     "List review items needing human attention.",
     "Do not modify artifacts.",
     ""),
    ("review.item.update", "runtime", "review", "item_update", "更新评审项", "review.item.update",
     "Update a review item status.",
     "Do not modify the original artifact body.",
     ""),
    ("memory.search", "memory", "record", "search", "搜索记忆", "memory.search",
     "Search user persistent memory for past preferences and facts.",
     "Do not store secrets.",
     "memory.search"),
    ("memory.list", "memory", "record", "list", "列出记忆", "memory.list",
     "List all memory records.",
     "Do not include secrets.",
     "memory.list"),
    ("memory.create", "memory", "record", "create", "创建记忆", "memory.create",
     "Create a new memory record.",
     "Do not store secrets.",
     "memory.create"),
    ("memory.confirm", "memory", "record", "confirm", "确认记忆", "memory.confirm",
     "Confirm or resolve a conflicting memory.",
     "Use for important memory only.",
     "memory.confirm"),
    ("memory.update", "memory", "record", "update", "更新记忆", "memory.update",
     "Update an existing memory record.",
     "Do not store secrets.",
     "memory.update"),
    ("memory.delete_soft", "memory", "record", "delete_soft", "软删除记忆", "memory.delete_soft",
     "Soft-delete a memory record.",
     "Do not hard-delete.",
     "memory.delete_soft"),
    ("memory.profile.get", "memory", "profile", "get", "读取 Profile", "memory.profile.get",
     "Read user profile from memory.",
     "Do not include secrets.",
     ""),
    ("memory.profile.set", "memory", "profile", "set", "更新 Profile", "memory.profile.set",
     "Update user profile in memory.",
     "Do not store secrets.",
     ""),
    ("report.markdown.render", "report_data", "report", "markdown_render", "渲染 Markdown 报告", "report.markdown.render",
     "Render a structured markdown report.",
     "Do not include raw sensitive config as final output.",
     ""),
    ("report.artifact.save", "report_data", "report", "artifact_save", "保存报告制品", "report.artifact.save",
     "Save a report as artifact. Use after render.",
     "Do not include raw sensitive config as final output.",
     ""),
    ("document.safe_summary.render", "report_data", "document", "safe_summary_render", "渲染安全摘要", "document.safe_summary.render",
     "Render a safe summary of scanned document.",
     "Do not include raw sensitive config.",
     ""),
    ("diagram.mermaid.render", "report_data", "diagram", "mermaid_render", "渲染 Mermaid 图", "diagram.mermaid.render",
     "Render a Mermaid.js diagram.",
     "Do not render untrusted raw diagrams.",
     ""),
    ("data.table.render", "report_data", "table", "render", "渲染表格", "data.table.render",
     "Render tabular data as a table.",
     "Do not include raw sensitive rows.",
     ""),
    ("data.table.extract", "report_data", "table", "extract", "提取表格", "data.table.extract",
     "Extract table from text or markdown.",
     "Do not execute embedded code.",
     ""),
    ("data.json.validate", "report_data", "json", "validate", "校验 JSON", "data.json.validate",
     "Validate JSON structure.",
     "Do not execute embedded code.",
     ""),
    ("data.yaml.validate", "report_data", "yaml", "validate", "校验 YAML", "data.yaml.validate",
     "Validate YAML structure.",
     "Do not execute embedded code.",
     ""),
    ("data.csv.summarize", "report_data", "csv", "summarize", "汇总 CSV", "data.csv.summarize",
     "Summarize CSV — columns, types, stats.",
     "Do not execute embedded code.",
     ""),
    ("text.redact", "report_data", "text", "redact", "文本脱敏", "text.redact",
     "Redact sensitive data from text.",
     "Use before persisting to memory or artifact.",
     "text.redact"),
    ("text.diff", "report_data", "text", "diff", "文本差异", "text.diff",
     "Compute diff between two texts.",
     "Do not execute embedded code.",
     "text.diff"),
    ("text.keywords.extract", "report_data", "text", "keywords_extract", "提取关键词", "text.keywords.extract",
     "Extract key terms and identifiers.",
     "Do not return secrets.",
     ""),
    ("text.classify", "report_data", "text", "classify", "文本分类", "text.classify",
     "Classify text into categories.",
     "Use only for safe, well-known categories.",
     "text.classify"),
    ("agent.role.list", "agent", "role", "list", "列出 Agent 角色", "agent.role.list",
     "List agent roles.",
     "Do not invent roles.",
     ""),
    ("agent.spawn", "agent", "subagent", "spawn", "创建子 Agent", "agent.spawn",
     "Spawn a sub-agent for a task.",
     "max_turns is enforced; do not bypass it.",
     "agent.spawn"),
    ("agent.team.run", "agent", "team", "run", "运行 Agent 团队", "agent.team.run",
     "Run a team of agents.",
     "max_turns and capability constraints apply.",
     ""),
    ("agent.result.get", "agent", "result", "get", "读取 Agent 结果", "agent.result.get",
     "Get a sub-agent's result.",
     "Do not return unredacted payloads.",
     ""),
    ("skill.list", "agent", "skill", "list", "列出技能", "skill.list",
     "List available skills.",
     "Do not enable untrusted skills.",
     "skill.list"),
    ("skill.load", "agent", "skill", "load", "加载技能", "skill.load",
     "Load a skill into current turn context.",
     "Do not load untrusted skills.",
     "skill.load"),
    ("skill.unload", "agent", "skill", "unload", "卸载技能", "skill.unload",
     "Unload a skill from context.",
     "Do not unload safety-relevant skills.",
     "skill.unload"),
    ("skill.search", "agent", "skill", "search", "搜索技能", "skill.search",
     "Search for a skill by name.",
     "Do not enable untrusted skills.",
     ""),
    ("skill.get", "agent", "skill", "get", "读取技能详情", "skill.get",
     "Get details about a skill.",
     "Do not return untrusted skill bodies.",
     ""),
    ("skill.create", "agent", "skill", "create", "创建新技能", "skill.create",
     "Create a new skill skeleton with SKILL.md and skill.yaml. Status: pending_review.",
     "Skills require manual review before activation.",
     ""),
    ("skill.install", "agent", "skill", "install", "安装技能", "skill.install",
     "Install a skill from local directory, archive URL (.zip/.tar.gz), or SKILL.md markdown content. Status: pending_review.",
     "Installed skills require manual review before activation.",
     ""),
    ("slash.command.list", "agent", "slash_command", "list", "列出 Slash 命令", "slash.command.list",
     "List registered slash commands.",
     "Do not invent commands.",
     "slash.command.list"),
    ("slash.command.run", "agent", "slash_command", "run", "执行 Slash 命令", "slash.command.run",
     "Run a registered slash command.",
     "Do not run unregistered commands.",
     "slash.command.run"),
]
