"""v3.6 canonical tool namespace — streamlined 12-category framework.

Categories are organized by capability domain, not backend module.
Tool IDs follow the pattern: domain.action or domain.subdomain.action.

Merges in v3.6:
  - exec.run: unifies host.shell/powershell/ssh/telnet
  - workspace.file.list: absorbs exists
  - workspace.file.read: absorbs preview
  - workspace.artifact.list: absorbs search
  - system.run.get: absorbs system.run.get + system.run.get
  - system.session.get: absorbs system.session.get + system.session.get
  - knowledge.source.reindex: absorbs reindex_all
  - knowledge.import: absorbs import.artifact
  - memory.search: list=true for list mode
  - memory.profile: unified get+set
"""

from __future__ import annotations


CATEGORY_DEFS: dict[str, dict[str, str]] = {
    "agent": {
        "name": "Agent 多 Agent",
        "description": "技能、子 Agent、角色、团队和结果读取。",
    },
    "browser": {
        "name": "Browser 浏览器",
        "description": "Playwright 浏览器自动化：导航、内容提取、截图。",
    },
    "code": {
        "name": "Code 代码搜索",
        "description": "跨代码库的 ripgrep 快速搜索。",
    },
    "config": {
        "name": "Config 配置分析",
        "description": "网络配置解析翻译和 PCAP 报文分析。",
    },
    "data": {
        "name": "Data 数据处理",
        "description": "报告渲染、表格/文本处理、JSON/YAML 校验和图表。",
    },
    "device": {
        "name": "Device 设备资产",
        "description": "网络设备资产清单查询、添加、删除。",
    },
    "exec": {
        "name": "Exec 命令执行",
        "description": "本机 Shell/Python/PowerShell 或远程 SSH/Telnet 命令执行（均需审批）。",
    },
    "git": {
        "name": "Git 版本管理",
        "description": "Git 仓库状态查看、差异对比、提交和推送。",
    },
    "knowledge": {
        "name": "Knowledge 知识库",
        "description": "知识库问答、检索、导入和索引管理。",
    },
    "memory": {
        "name": "Memory 记忆",
        "description": "记忆搜索、创建、确认、profile 和更新。",
    },
    "system": {
        "name": "System 系统自省",
        "description": "运行诊断、会话管理、审计和评审。",
    },
    "web": {
        "name": "Web 外部资料",
        "description": "公开 Web 搜索、官方文档、新闻、天气预报和网页摘要。",
    },
    "workspace": {
        "name": "Workspace 工作区",
        "description": "工作区文件、Artifact 制品和 metadata 元数据。",
    },
}


NS_DATA = [
    ('exec.run', 'exec', 'shell', 'run', '命令执行', 'exec.run',
     'Execute a command on a target machine. target=local|ssh|telnet, shell=cmd|powershell. Local: optional working_dir/env_vars/timeout. Remote: host/port/username/password.',
     'NEVER use for destructive commands (reload/erase/format/rm -rf). Do NOT store or expose credentials in output.', 'exec.run'),
    ('exec.python', 'exec', 'python', 'run', 'Python 执行', 'exec.python',
     'Run Python on the local host (AST-sandboxed). Use for approved computation, data processing.',
     'Do not use for network device access.', 'exec.python'),
    ('exec.slash', 'exec', 'slash', 'run', 'Slash 命令', 'exec.slash',
     'Run a registered slash command on the local host.',
     'Do not use for unregistered commands.', 'exec.slash'),
    ('device.list', 'device', 'asset', 'list', '列出设备资产', 'device.list',
     'List all device assets. Returns name, type, vendor, model, IP, protocol, port.',
     'Do not fabricate assets that were not returned.', 'device.list'),
    ('device.get', 'device', 'asset', 'get', '获取设备详情', 'device.get',
     'Get full detail for a single device by asset_id. Returns host/port/protocol/credentials for login.',
     'Do not expose credentials in LLM output.', 'device.get'),
    ('device.add', 'device', 'asset', 'add', '添加设备', 'device.add',
     'Add a network device asset. Requires approval. Provide device_name, host, protocol, port, vendor, username, password.',
     'Do not add without explicit user request.', 'device.add'),
    ('device.delete', 'device', 'asset', 'delete', '删除设备', 'device.delete',
     'Soft-delete a device by asset_id (tombstone, recoverable).',
     'Confirm with user before deleting.', 'device.delete'),
    ('workspace.file.list', 'workspace', 'file', 'list', '列出工作区文件', 'workspace.file.list',
     'List workspace files with names and sizes. Use query param to filter by name.',
     'Do not cross workspaces.', 'workspace.file.list'),
    ('workspace.file.read', 'workspace', 'file', 'read', '读取工作区文件', 'workspace.file.read',
     'Read a workspace file. Use offset=N to start from line N (pagination). limit controls max chars. MUST call before config.analysis.run.',
     'Do not use for artifacts, knowledge base, or arbitrary absolute paths.', 'workspace.file.read'),
    ('workspace.file.read_image', 'workspace', 'file', 'read_image', '读取图片信息', 'workspace.file.read_image',
     'Read image file metadata — dimensions, format, size. Does NOT OCR.',
     'Do not use for text/code files.', 'workspace.file.read_image'),
    ('workspace.file.edit', 'workspace', 'file', 'edit', '编辑工作区文件', 'workspace.file.edit',
     'Edit a file with string replacement. Requires approval.',
     'Do not use for absolute paths outside workspace.', 'workspace.file.edit'),
    ('workspace.file.patch', 'workspace', 'file', 'patch', '工作区文件补丁', 'workspace.file.patch',
     'Apply a diff/patch to a file. Requires approval.',
     'Do not use for absolute paths outside workspace.', 'workspace.file.patch'),
    ('workspace.file.write_artifact', 'workspace', 'file', 'write_artifact', '写入制品文件', 'workspace.file.write_artifact',
     'Write content and register as artifact.',
     'Do not write to arbitrary paths.', 'workspace.file.write_artifact'),
    ('file.references', 'workspace', 'file', 'references', '查询文件引用', 'file.references',
     'Query cross-references for a FileStore file.',
     None, 'file.references'),
    ('file.import_workspace_path', 'workspace', 'file', 'import', '导入文件到FileStore', 'file.import_workspace_path',
     'Import a workspace-relative file into FileStore.',
     'Path must be in allowed current directories.', 'file.import_workspace_path'),
    ('workspace.metadata.get', 'workspace', 'metadata', 'get', '读取工作区元数据', 'workspace.metadata.get',
     'Get workspace metadata and stats.',
     'Do not return secrets.', 'workspace.metadata.get'),
    ('workspace.artifact.list', 'workspace', 'artifact', 'list', '列出制品', 'workspace.artifact.list',
     'List workspace artifacts. Use query param to filter by title or type.',
     'Do not return artifact bodies; use workspace.artifact.read.', 'workspace.artifact.list'),
    ('workspace.artifact.read', 'workspace', 'artifact', 'read', '读取制品', 'workspace.artifact.read',
     "Read an artifact's content.",
     'Do not use to bypass artifact safety policy.', 'workspace.artifact.read'),
    ('workspace.artifact.save', 'workspace', 'artifact', 'save', '保存制品', 'workspace.artifact.save',
     'Save content as a new artifact.',
     'Do not save secrets.', 'workspace.artifact.save'),
    ('workspace.artifact.diff', 'workspace', 'artifact', 'diff', '制品差异', 'workspace.artifact.diff',
     'Diff two artifacts or files.',
     'Do not use for non-artifact files.', 'workspace.artifact.diff'),
    ('workspace.artifact.export', 'workspace', 'artifact', 'export', '导出制品', 'workspace.artifact.export',
     'Export an artifact to external format.',
     'Do not export outside workspace.', 'workspace.artifact.export'),
    ('workspace.artifact.tag', 'workspace', 'artifact', 'tag', '制品标签', 'workspace.artifact.tag',
     'Tag an artifact.',
     'Do not modify artifact body content.', 'workspace.artifact.tag'),
    ('workspace.artifact.delete_soft', 'workspace', 'artifact', 'delete_soft', '软删除制品', 'artifact.delete_soft',
     'Soft-delete an artifact. Requires approval.',
     'Do not perform hard deletion.', 'workspace.artifact.delete_soft'),
    ('workspace.document.pdf.extract_text', 'workspace', 'document', 'pdf_extract_text', '提取 PDF 文本', 'workspace.document.pdf.extract_text',
     'Extract text from a PDF.',
     'Do not use for non-PDF files.', 'workspace.document.pdf.extract_text'),
    ('knowledge.search', 'knowledge', 'search', 'search', '知识库检索', 'knowledge.search',
     'Search the workspace knowledge base for indexed documents and chunks.',
     'Do not return unredacted full text.', 'knowledge.search'),
    ('knowledge.read', 'knowledge', 'read', 'read', '读取知识内容', 'knowledge.read',
     'Read knowledge content at level: chunk (default), source, or parent.',
     'Do not return unredacted secrets.', 'knowledge.read'),
    ('knowledge.source.list', 'knowledge', 'source', 'list', '列出知识源', 'knowledge.source.list',
     'List all indexed knowledge sources with status and count.',
     None, 'knowledge.source.list'),
    ('knowledge.chunk.list', 'knowledge', 'chunk', 'list', '列出知识块', 'knowledge.chunk.list',
     'List all chunks for a knowledge source.',
     None, 'knowledge.chunk.list'),
    ('knowledge.source.manage', 'knowledge', 'source', 'manage', '管理知识源', 'knowledge.source.manage',
     'Manage a knowledge source: action=disable|delete|reindex.',
     None, 'knowledge.source.manage'),
    ('knowledge.source.reindex', 'knowledge', 'source', 'reindex', '重建索引', 'knowledge.source.reindex',
     'Reindex knowledge source(s). source_id=ALL to reindex everything (destructive, slow).',
     'Do not run reindex_all in production without explicit approval.', 'knowledge.source.reindex'),
    ('knowledge.import', 'knowledge', 'import', 'import', '导入知识', 'knowledge.import',
     'Import a file/document/artifact into the workspace knowledge base. Auto-detects format. Use artifact_id param for artifact import.',
     None, 'knowledge.import'),
    ('knowledge.not_found.explain', 'knowledge', 'not_found', 'explain', '解释未命中', 'knowledge.not_found.explain',
     'Explain why a search returned no results. Use only when no results.',
     None, 'knowledge.not_found.explain'),
    ('memory.search', 'memory', 'record', 'search', '搜索记忆', 'memory.search',
     'Search user persistent memory. list=true to list all records without query.',
     'Do not store secrets.', 'memory.search'),
    ('memory.manage', 'memory', 'record', 'manage', '管理记忆', 'memory.manage',
     'Manage memory records. action=create|update|confirm|delete.',
     'Do not store secrets.', 'memory.manage'),
    ('memory.profile', 'memory', 'profile', 'manage', 'Profile 管理', 'memory.profile',
     'Read or update user profile from memory. action=get (default) or set (needs field+value).',
     'Do not include secrets.', 'memory.profile'),
    ('system.diagnostics', 'system', 'health', 'diagnostics', '运行诊断', 'system.diagnostics',
     'Run diagnostics on agent runtime. level=health (quick check) or full (default, complete scan).',
     'Do not include sensitive trace payloads.', 'system.diagnostics'),
    ('system.run.get', 'system', 'run', 'get', '运行记录', 'system.run.get',
     'Get run records. list=true for list of recent runs, or provide run_id for detailed summary.',
     'Do not return full trace bodies.', 'system.run.get'),
    ('system.session.get', 'system', 'session', 'get', '会话管理', 'system.session.get',
     'Get session info. list=true for active sessions list, or provide session_id for summary.',
     'Do not include sensitive trace payloads.', 'system.session.get'),
    ('system.session.checkpoint', 'system', 'session', 'checkpoint', '会话检查点', 'system.session.checkpoint',
     'Create session checkpoint for rewind.',
     'Do not include secrets.', 'system.session.checkpoint'),
    ('system.session.rewind', 'system', 'session', 'rewind', '会话回滚', 'system.session.rewind',
     'Rewind session to checkpoint (destructive).',
     'Do not include secrets in rewind steps.', 'system.session.rewind'),
    ('system.session.export', 'system', 'session', 'export', '导出会话', 'system.session.export',
     'Export session to JSON/Markdown.',
     'Do not include secrets in exported artifacts.', 'system.session.export'),
    ('system.session.snapshot', 'system', 'session', 'snapshot', '会话快照', 'system.session.snapshot',
     'Create or list session snapshots. action=create (default) or list.',
     'Do not include secrets in snapshots.', 'system.session.snapshot'),
    ('system.review.item.list', 'system', 'review', 'item_list', '列出评审项', 'system.review.item.list',
     'List review items needing human attention.',
     'Do not modify artifacts.', 'system.review.item.list'),
    ('system.review.item.update', 'system', 'review', 'item_update', '更新评审项', 'system.review.item.update',
     'Update a review item status.',
     'Do not modify original artifact body.', 'system.review.item.update'),
    ('web.search', 'web', 'search', 'search', '公开 Web 搜索', 'web.search',
     'Search the web. source=web (default), docs (vendor docs), or news (recent news). Falls back to docs when unavailable.',
     'Do not query private/login-walled URLs.', 'web.search'),
    ('web.page.process', 'web', 'page', 'process', '网页操作', 'web.page.process',
     'Process a web page. action=summarize (default), extract_links, or save_artifact.',
     'Do not query private/login-walled URLs.', 'web.page.process'),
    ('web.weather', 'web', 'weather', 'current_and_forecast', '天气查询', 'web.weather',
     'Get weather. days=1 for current, 2-10 for forecast. Powered by Open-Meteo.',
     None, 'web.weather'),
    ('browser.navigate', 'browser', 'nav', 'navigate', '浏览器导航', 'browser.navigate',
     'Open browser and navigate to URL. Returns page title + visible text.',
     'Do not access internal/private URLs without permission.', 'browser.navigate'),
    ('browser.extract', 'browser', 'extract', 'extract', '浏览器内容提取', 'browser.extract',
     'Extract text from a specific element on a web page by CSS selector.',
     'Do not use on login-required pages.', 'browser.extract'),
    ('browser.screenshot', 'browser', 'capture', 'screenshot', '网页截图', 'browser.screenshot',
     'Take a screenshot of a web page. full_page=true for full page capture. Returns base64 PNG.',
     'Do not capture login-required pages.', 'browser.screenshot'),
    ('browser.click', 'browser', 'interact', 'click', '网页点击', 'browser.click',
     'Click an element on the currently loaded page by CSS selector. Navigate to page first.',
     'Do not use on login-required pages.', 'browser.click'),
    ('git.status', 'git', 'status', 'status', 'Git 状态检查', 'git.status',
     'Check git repo status: modified, staged, untracked files. Always run first.',
     'Do not use without validating repo path.', 'git.status'),
    ('git.diff', 'git', 'diff', 'diff', 'Git 差异', 'git.diff',
     'Show git diff (unstaged or staged). Review before committing.',
     'Avoid very large diffs — use file_path to scope.', 'git.diff'),
    ('git.log', 'git', 'log', 'log', 'Git 提交历史', 'git.log',
     'View recent git commits with one-line summaries.',
     None, 'git.log'),
    ('git.commit', 'git', 'commit', 'commit', 'Git 提交', 'git.commit',
     'Stage and commit changes. ALWAYS run git.status + git.diff first. Requires user approval.',
     'NEVER commit without user confirmation.', 'git.commit'),
    ('git.push', 'git', 'push', 'push', 'Git 推送', 'git.push',
     'Push commits to remote. Requires user approval.',
     'NEVER push without user confirmation.', 'git.push'),
    ('agent.role.list', 'agent', 'role', 'list', '列出 Agent 角色', 'agent.role.list',
     'List agent roles.',
     'Do not invent roles.', 'agent.role.list'),
    ('agent.spawn', 'agent', 'subagent', 'spawn', '创建子 Agent', 'agent.spawn',
     'Spawn a sub-agent for a task. max_turns enforced.',
     'Do not bypass max_turns.', 'agent.spawn'),
    ('agent.team.run', 'agent', 'team', 'run', '运行 Agent 团队', 'agent.team.run',
     'Run a team of agents.',
     'max_turns and capability constraints apply.', 'agent.team.run'),
    ('agent.result.get', 'agent', 'result', 'get', '读取 Agent 结果', 'agent.result.get',
     "Get a sub-agent's result.",
     'Do not return unredacted payloads.', 'agent.result.get'),
    ('tool.catalog.search', 'agent', 'tool_catalog', 'search', '搜索工具目录', 'tool.catalog.search',
     'Search the full tool catalog to discover specialized tools not currently visible.',
     'Use only for discovery — do not execute work.', 'tool.catalog.search'),
    ('skill.list', 'agent', 'skill', 'list', '列出技能', 'skill.list',
     'List available capability-backed skills and their related modules/tools.',
     'Read-only discovery; do not claim a skill was executed.', 'skill.list'),
    ('skill.find', 'agent', 'skill', 'find', '搜索技能', 'skill.find',
     'Search available capability-backed skills by user intent, domain, or keyword.',
     'Read-only discovery; load or call the returned tools separately.', 'skill.find'),
    ('skill.load', 'agent', 'skill', 'load', '加载技能', 'skill.load',
     'Load one capability-backed skill and return its prompt hints, modules, and tools.',
     'Read-only load; it does not execute the business task by itself.', 'skill.load'),
    ('skill.inspect', 'agent', 'skill', 'inspect', '检查技能', 'skill.inspect',
     'Inspect one capability-backed skill in detail.',
     'Read-only inspection; do not expose hidden implementation data.', 'skill.inspect'),
    ('config.analysis.run', 'config', 'config_analysis', 'run', '配置分析', 'config.analysis.run',
     'Run config analysis: parse, translate, extract_interfaces, extract_routes, diff, summarize.',
     'Do not claim translated config is production-ready.', 'config.analysis.run'),
    ('pcap.analysis.run', 'config', 'pcap_analysis', 'run', 'PCAP 分析', 'pcap.analysis.run',
     'Run PCAP analysis: parse, session, filter, align.',
     'Do not use for text configs.', 'pcap.analysis.run'),
    ('code.search', 'code', 'search', 'search', '代码搜索', 'code.search',
     'Search codebase using ripgrep. Returns matching lines with file paths and line numbers.',
     None, 'code.search'),
    ('report.markdown.render', 'data', 'report', 'markdown_render', '渲染 Markdown 报告', 'report.markdown.render',
     'Render a structured markdown report.',
     None, 'report.markdown.render'),
    ('report.artifact.save', 'data', 'report', 'artifact_save', '保存报告制品', 'report.artifact.save',
     'Save a report as artifact. Use after render.',
     None, 'report.artifact.save'),
    ('document.safe_summary.render', 'data', 'document', 'safe_summary_render', '渲染安全摘要', 'document.safe_summary.render',
     'Render a safe summary of scanned document.',
     'Do not include raw sensitive config.', 'document.safe_summary.render'),
    ('diagram.mermaid.render', 'data', 'diagram', 'mermaid_render', '渲染 Mermaid 图', 'diagram.mermaid.render',
     'Render a Mermaid.js diagram.',
     'Do not render untrusted raw diagrams.', 'diagram.mermaid.render'),
    ('data.table.render', 'data', 'table', 'render', '渲染表格', 'data.table.render',
     'Render tabular data as a table.',
     'Do not include raw sensitive rows.', 'data.table.render'),
    ('data.table.extract', 'data', 'table', 'extract', '提取表格', 'data.table.extract',
     'Extract table from text or markdown.',
     'Do not execute embedded code.', 'data.table.extract'),
    ('data.validate', 'data', 'data', 'validate', '数据校验', 'data.validate',
     'Validate data structure. format=json or yaml.',
     'Do not execute embedded code.', 'data.validate'),
    ('data.csv.summarize', 'data', 'csv', 'summarize', '汇总 CSV', 'data.csv.summarize',
     'Summarize CSV — columns, types, stats.',
     'Do not execute embedded code.', 'data.csv.summarize'),
    ('text.analyze', 'data', 'text', 'analyze', '文本分析', 'text.analyze',
     'Analyze text. action=redact|diff|keywords|classify.',
     'Do not execute embedded code.', 'text.analyze'),
]
