"""v2.2 tool namespace data.

Each tuple is:
canonical, execution, legacy aliases, category, group, action,
display name, short label, usage hint, not_for.
"""

NS_DATA = [
    ("agent.result.get", "agent.get_result", ("agent.get_result",), "agent", "result", "get", "获取子 Agent 结果", "取结果", "读取已完成子 Agent 的安全结果摘要", "不要用于启动新 Agent"),
    ("agent.role.list", "agent.list_roles", ("agent.list_roles",), "agent", "role", "list", "列出 Agent 角色", "角色", "查看 planner/worker/reviewer 等可用角色", "不要用于运行团队任务"),
    ("agent.spawn", "agent.spawn", ("agent.spawn",), "agent", "subagent", "spawn", "启动子 Agent", "子任务", "把受限任务交给子 Agent 执行", "不要递归启动子 Agent"),
    ("agent.team.run", "agent.team", ("agent.team",), "agent", "team", "run", "运行 Agent 团队预览", "团队", "预览多 Agent 协作流程", "不要当作生产自动化"),
    ("workspace.artifact.diff", "artifact.diff", ("artifact.diff",), "workspace", "artifact", "diff", "比较制品", "制品差异", "比较两个 workspace artifact 的安全摘要", "不要读取任意本地路径"),
    ("workspace.artifact.export", "artifact.export", ("artifact.export",), "workspace", "artifact", "export", "导出制品", "导出", "导出 workspace artifact 的安全格式", "不要导出 secret artifact"),
    ("workspace.artifact.list", "artifact.list", ("artifact.list",), "workspace", "artifact", "list", "列出制品", "制品列表", "列出 workspace 内 artifact 元数据", "不要用于文件系统遍历"),
    ("workspace.artifact.read", "artifact.read", ("artifact.read",), "workspace", "artifact", "read", "读取制品", "读制品", "读取允许访问的 artifact 安全内容", "不要绕过敏感内容策略"),
    ("workspace.artifact.save", "artifact.save_result", ("artifact.save_result",), "workspace", "artifact", "save", "保存结果制品", "存制品", "把工具结果保存为 workspace artifact", "不要保存未脱敏 secret"),
    ("network.config.translate", "config_translation.translate_config", ("config_translation.translate_config",), "network", "config", "translate", "翻译网络配置", "配置翻译", "离线翻译网络设备配置并产出复核项", "不要登录真实设备或下发配置"),
    ("data.csv.summarize", "csv.summarize", ("csv.summarize",), "report_data", "csv", "summarize", "汇总 CSV", "CSV 汇总", "汇总 CSV/表格文本的安全统计", "不要处理超大原始文件"),
    ("diagram.mermaid.render", "diagram.render_mermaid", ("diagram.render_mermaid",), "report_data", "diagram", "render", "渲染 Mermaid 图", "图表", "生成 Mermaid 图表文本", "不要渲染不可信脚本"),
    ("document.safe_summary.render", "doc.render_from_safe_summary", ("doc.render_from_safe_summary",), "report_data", "document", "render", "渲染安全摘要文档", "文档", "从安全摘要生成文档片段", "不要包含原始敏感配置"),
    ("workspace.file.edit", "file.edit", ("file.edit",), "workspace", "file", "edit", "编辑工作区文件", "编辑文件", "替换 workspace 内文本文件片段", "不要编辑绝对路径或 secret 文件"),
    ("workspace.file.exists", "file.exists", ("file.exists",), "workspace", "file", "exists", "检查文件存在", "存在", "检查 workspace 文件是否存在", "不要用于 artifact id"),
    ("workspace.file.list", "file.list", ("file.list",), "workspace", "file", "list", "列出工作区文件", "列文件", "列出 workspace 文件", "不要列出系统目录"),
    ("workspace.file.patch", "file.patch", ("file.patch",), "workspace", "file", "patch", "应用文件补丁", "补丁", "对 workspace 文件应用 unified diff", "不要修改工作区之外路径"),
    ("workspace.file.read", "file.read", ("file.read",), "workspace", "file", "read", "读取工作区文件", "读文件", "读取 workspace 内完整文本文件", "不要用于 artifact、知识库或任意绝对路径"),
    ("data.json.validate", "json.validate", ("json.validate",), "report_data", "json", "validate", "校验 JSON", "JSON", "校验 JSON 文本结构", "不要执行 JSON 中的代码"),
    ("knowledge.source.delete", "knowledge.delete_source", ("knowledge.delete_source",), "knowledge", "source", "delete", "删除知识源", "删源", "删除 workspace 知识源记录", "不要删除 artifact 本体"),
    ("knowledge.source.disable", "knowledge.disable_source", ("knowledge.disable_source",), "knowledge", "source", "disable", "停用知识源", "停源", "停用知识源参与检索", "不要删除源内容"),
    ("knowledge.import.document", "knowledge.import_document", ("knowledge.import_document",), "knowledge", "import", "document", "导入文档", "导文档", "导入文档内容到知识库", "不要导入未授权敏感文件"),
    ("knowledge.import.file", "knowledge.import_file", ("knowledge.import_file",), "knowledge", "import", "file", "导入文件", "导文件", "导入 workspace 文件到知识库", "不要导入工作区外文件"),
    ("knowledge.chunk.list", "knowledge.list_chunks", ("knowledge.list_chunks",), "knowledge", "chunk", "list", "列出知识块", "块列表", "列出某知识源的 chunks", "不要返回全文"),
    ("knowledge.source.list", "knowledge.list_sources", ("knowledge.list_sources",), "knowledge", "source", "list", "列出知识源", "源列表", "列出知识库 sources", "不要读取完整源内容"),
    ("knowledge.query", "knowledge.query", ("knowledge.query",), "knowledge", "query", "answer", "知识库问答", "知识问答", "基于知识库安全摘录回答问题", "不要凭空引用未检索内容"),
    ("knowledge.chunk.read", "knowledge.read_chunk", ("knowledge.read_chunk",), "knowledge", "chunk", "read", "读取知识块", "读块", "读取安全 chunk 摘要", "不要返回未经脱敏全文"),
    ("knowledge.parent.read", "knowledge.read_parent", ("knowledge.read_parent",), "knowledge", "parent", "read", "读取父文档摘要", "父文档", "读取 chunk 所属父文档安全摘要", "不要泄露绝对路径"),
    ("knowledge.source.read", "knowledge.read_source", ("knowledge.read_source",), "knowledge", "source", "read", "读取知识源", "读源", "读取知识源安全元数据", "不要读取 secret 原文"),
    ("knowledge.source.reindex", "knowledge.reindex_source", ("knowledge.reindex_source",), "knowledge", "source", "reindex", "重建知识源索引", "重索引", "重建单个知识源索引", "不要批量重建全部源"),
    ("knowledge.search", "knowledge.search_chunks", ("knowledge.search_chunks",), "knowledge", "search", "chunks", "搜索知识块", "搜索", "搜索知识库安全 chunks", "不要作为 Web 搜索替代"),
    ("memory.confirm", "memory.confirm", ("memory.confirm",), "memory", "record", "confirm", "确认记忆", "确认", "确认并写入重要记忆", "不要自动写入未经确认偏好"),
    ("memory.create", "memory.create", ("memory.create",), "memory", "record", "create", "创建记忆", "记忆", "创建短期/长期记忆记录", "不要保存 secret"),
    ("memory.delete_soft", "memory.delete_soft", ("memory.delete_soft",), "memory", "record", "delete_soft", "软删除记忆", "删记忆", "软删除记忆记录", "不要物理删除数据"),
    ("memory.profile.get", "memory.get_profile", ("memory.get_profile",), "memory", "profile", "get", "读取记忆 Profile", "读档案", "读取用户偏好档案", "不要读取 secret"),
    ("memory.list", "memory.list", ("memory.list",), "memory", "record", "list", "列出记忆", "记忆列表", "列出记忆记录摘要", "不要返回敏感全文"),
    ("memory.search", "memory.search", ("memory.search",), "memory", "record", "search", "搜索记忆", "搜记忆", "搜索记忆摘要", "不要替代知识库检索"),
    ("memory.profile.set", "memory.set_profile", ("memory.set_profile",), "memory", "profile", "set", "更新记忆 Profile", "写档案", "更新用户偏好档案", "不要写入 secret"),
    ("memory.update", "memory.update", ("memory.update",), "memory", "record", "update", "更新记忆", "更新", "更新既有记忆记录", "不要绕过确认策略"),
    ("web.news.search", "news.search", ("news.search",), "web", "news", "search", "搜索新闻", "新闻", "搜索公开新闻信息", "不要用于本地文件"),
    ("network.interface.extract", "parser.extract_interfaces", ("parser.extract_interfaces",), "network", "interface", "extract", "提取接口", "接口", "离线提取配置中的接口信息", "不要登录设备"),
    ("network.route.extract", "parser.extract_routes", ("parser.extract_routes",), "network", "route", "extract", "提取路由", "路由", "离线提取配置中的路由信息", "不要登录设备"),
    ("network.config.parse", "parser.parse_config_text", ("parser.parse_config_text",), "network", "config", "parse", "解析网络配置", "配置解析", "离线解析网络配置文本", "不要执行配置"),
    ("workspace.document.pdf.extract_text", "pdf.extract_text", ("pdf.extract_text",), "workspace", "document", "extract_text", "提取 PDF 文本", "PDF", "提取 workspace PDF 文本", "不要读取非 PDF 或工作区外文件"),
    ("host.powershell.exec", "powershell.exec", ("powershell.exec",), "host", "powershell", "exec", "执行本机 PowerShell", "PowerShell", "在本机执行已审批 PowerShell 脚本", "不用于网络设备 SSH/Telnet/SNMP"),
    ("host.python.exec", "python.exec", ("python.exec",), "host", "python", "exec", "执行本机 Python", "Python", "在本机执行已审批 Python 脚本", "不用于网络设备或无审批执行"),
    ("report.markdown.render", "report.render_markdown", ("report.render_markdown",), "report_data", "report", "render_markdown", "渲染 Markdown 报告", "报告", "从安全结果渲染 Markdown 报告", "不要包含原始 secret"),
    ("report.artifact.save", "report.save_artifact", ("report.save_artifact",), "report_data", "report", "save_artifact", "保存报告制品", "存报告", "把报告保存为 workspace artifact", "不要保存敏感全文"),
    ("review.item.list", "review.list_items", ("review.list_items",), "runtime", "review", "list", "列出复核项", "复核", "列出人工复核项", "不要自动关闭复核"),
    ("review.item.update", "review.update_item", ("review.update_item",), "runtime", "review", "update", "更新复核项", "更复核", "更新人工复核项状态", "不要绕过用户决定"),
    ("run.summary.get", "run.get_summary", ("run.get_summary",), "runtime", "run", "summary_get", "获取运行摘要", "运行摘要", "读取 run 安全摘要", "不要读取 trace 全量"),
    ("run.list", "run.list_recent", ("run.list_recent",), "runtime", "run", "list", "列出最近运行", "运行列表", "列出最近 runs", "不要跨 workspace 泄露"),
    ("runtime.diagnostics", "runtime.diagnostics", ("runtime.diagnostics",), "runtime", "health", "diagnostics", "运行诊断", "诊断", "读取 runtime 诊断", "不要修改状态"),
    ("runtime.health", "runtime.health", ("runtime.health",), "runtime", "health", "get", "运行健康", "健康", "读取 runtime 健康状态", "不要执行修复"),
    ("session.checkpoint", "session.checkpoint", ("session.checkpoint",), "runtime", "session", "checkpoint", "创建会话检查点", "检查点", "创建当前 session 检查点", "不要当作完整备份"),
    ("session.export", "session.export", ("session.export",), "runtime", "session", "export", "导出会话", "导出会话", "导出 session 安全摘要", "不要导出 secret"),
    ("session.summary.get", "session.get_summary", ("session.get_summary",), "runtime", "session", "summary_get", "获取会话摘要", "会话摘要", "读取 session 摘要", "不要读取其它 workspace"),
    ("session.list", "session.list", ("session.list",), "runtime", "session", "list", "列出会话", "会话", "列出 workspace sessions", "不要跨 workspace"),
    ("session.snapshot.list", "session.list_snapshots", ("session.list_snapshots",), "runtime", "session", "snapshot_list", "列出会话快照", "快照列表", "列出 session snapshots", "不要恢复状态"),
    ("session.rewind", "session.rewind", ("session.rewind",), "runtime", "session", "rewind", "回退会话", "回退", "回退到 session snapshot", "不要声称完整 checkpoint"),
    ("session.snapshot.create", "session.snapshot", ("session.snapshot",), "runtime", "session", "snapshot_create", "创建会话快照", "快照", "创建 session snapshot", "不要复制 secret"),
    ("host.shell.exec", "shell.exec", ("shell.exec",), "host", "shell", "exec", "执行本机 Shell", "Shell", "在本机执行已审批 Shell 命令", "不用于网络设备 SSH/Telnet/SNMP"),
    ("skill.create", "skill.create", ("skill.create",), "agent", "skill", "create", "创建技能", "建技能", "创建本地 agent skill 草案", "不要自动启用未经审查技能"),
    ("skill.find", "skill.find_skills", ("skill.find_skills",), "agent", "skill", "find", "查找技能", "找技能", "查找可用技能", "不要加载技能"),
    ("skill.inspect", "skill.inspect", ("skill.inspect",), "agent", "skill", "inspect", "检查技能", "查技能", "查看技能详情", "不要执行技能"),
    ("skill.list", "skill.list", ("skill.list",), "agent", "skill", "list", "列出技能", "技能", "列出已注册技能", "不要加载技能"),
    ("skill.load", "skill.load", ("skill.load",), "agent", "skill", "load", "加载技能", "加载", "加载指定技能提示", "不要加载未知来源技能"),
    ("skill.request_load", "skill.request_load", ("skill.request_load",), "agent", "skill", "request_load", "请求加载技能", "请求技能", "创建技能加载请求", "不要绕过用户确认"),
    ("host.command.slash_run", "slash.run", ("slash.run",), "host", "command", "slash_run", "运行 Slash 命令", "Slash", "执行内置 slash 命令", "不要执行任意 shell"),
    ("data.table.extract", "table.extract", ("table.extract",), "report_data", "table", "extract", "提取表格", "表格提取", "从文本提取表格数据", "不要解析 secret 原文"),
    ("data.table.render", "table.render_markdown", ("table.render_markdown",), "report_data", "table", "render", "渲染 Markdown 表格", "表格", "把结构化数据渲染为 Markdown 表格", "不要包含敏感字段"),
    ("text.classify", "text.classify", ("text.classify",), "report_data", "text", "classify", "文本分类", "分类", "对短文本做本地规则分类", "不要当作安全审计结论"),
    ("text.diff", "text.diff", ("text.diff",), "report_data", "text", "diff", "文本差异", "差异", "比较两段文本差异", "不要处理超大配置全文"),
    ("text.keywords.extract", "text.extract_keywords", ("text.extract_keywords",), "report_data", "text", "keywords_extract", "提取关键词", "关键词", "提取文本关键词", "不要当作知识库搜索"),
    ("text.redact", "text.redact", ("text.redact",), "report_data", "text", "redact", "文本脱敏", "脱敏", "对文本进行安全脱敏", "不要保证强隔离沙箱"),
    ("web.weather.current", "weather.current", ("weather.current",), "web", "weather", "current", "当前天气", "天气", "查询公开天气信息", "不要用于本机环境状态"),
    ("web.weather.forecast", "weather.forecast", ("weather.forecast",), "web", "weather", "forecast", "天气预报", "预报", "查询公开天气预报", "不要用于网络设备状态"),
    ("web.page.extract_links", "web.extract_links", ("web.extract_links",), "web", "page", "extract_links", "提取网页链接", "链接", "从网页摘要中提取链接", "不要抓取私有站点"),
    ("web.page.summarize", "web.fetch_summary", ("web.fetch_summary",), "web", "page", "summarize", "总结网页", "网页摘要", "获取公开网页摘要", "不要绕过 robots 或登录墙"),
    ("web.docs.official_search", "web.official_doc_search", ("web.official_doc_search",), "web", "docs", "official_search", "搜索官方文档", "官方文档", "搜索厂商/标准官方资料", "不要用于本地文件"),
    ("web.page.save_artifact", "web.save_to_artifact", ("web.save_to_artifact",), "web", "page", "save_artifact", "保存网页摘要", "存网页", "把网页安全摘要保存为 artifact", "不要保存未授权全文"),
    ("web.search", "web.search", ("web.search",), "web", "search", "general", "Web 搜索", "搜索", "搜索公开 Web 信息", "不要用于 private/local 文件"),
    ("workspace.metadata.get", "workspace.get_metadata", ("workspace.get_metadata",), "workspace", "metadata", "get", "读取工作区元数据", "元数据", "读取 workspace 安全元数据", "不要返回 secret"),
    ("workspace.file.list_all", "workspace.list_files", ("workspace.list_files", "workspace.file.list"), "workspace", "file", "list_all", "列出工作区文件树", "文件树", "列出 workspace 文件树预览", "不要列出系统目录"),
    ("workspace.file.path_exists", "workspace.path_exists", ("workspace.path_exists", "workspace.file.exists"), "workspace", "file", "path_exists", "检查工作区路径", "路径存在", "检查 workspace 路径存在性", "不要检查工作区外路径"),
    ("workspace.file.preview", "workspace.read_text_preview", ("workspace.read_text_preview",), "workspace", "file", "preview", "预览工作区文本", "预览", "读取 workspace 文本文件安全预览", "不要读取完整大文件"),
    ("workspace.file.write_artifact", "workspace.write_artifact_file", ("workspace.write_artifact_file",), "workspace", "file", "write_artifact", "写入制品文件", "写制品", "向 workspace artifact 输出区写文件", "不要写任意路径"),
    ("data.yaml.validate", "yaml.validate", ("yaml.validate",), "report_data", "yaml", "validate", "校验 YAML", "YAML", "校验 YAML 文本结构", "不要执行 YAML 内容"),
]
