"""agent.modules.inspection.report

v4.0: raw-output Markdown generator.  No parser results, no
findings — just the raw command output formatted per device.
The LLM reads this and produces its own analysis.
"""

from __future__ import annotations

from datetime import datetime, timezone

from .models import InspectionTask


def render_markdown(task: InspectionTask, *, asset_id: str = "") -> str:
    """Format raw inspection output as Markdown for LLM consumption.

    When ``asset_id`` is provided, only that device's output is rendered.
    This allows the main agent to dispatch one sub-agent per device
    for isolated analysis, avoiding context window overflow.
    """
    out: list[str] = []
    out.append(f"# 巡检原始输出")
    out.append("")
    out.append(f"- **任务ID**: {task.task_id}")
    out.append(f"- **巡检类型**: {task.profile_display_name or task.profile_id}")
    out.append("")

    if asset_id:
        # ── single-device mode ──
        d = task.devices.get(asset_id)
        if d is None:
            out.append(f"> ⚠️ 设备 {asset_id} 不在本次巡检结果中。")
            out.append("")
            return "\n".join(out)
        _render_one_device(out, d)
    else:
        # ── full report mode ──
        out.append(f"- **开始时间**: {task.started_at or '—'}")
        out.append(f"- **结束时间**: {task.finished_at or '—'}")
        out.append(f"- **状态**: {task.status}")
        out.append("")
        out.append(f"**总设备**: {task.total_assets}  ·  "
                   f"成功 {task.succeeded}  ·  "
                   f"失败 {task.failed}  ·  "
                   f"部分 {task.partial}  ·  "
                   f"跳过 {task.skipped}")
        out.append("")

        scope = render_scope(task)
        if scope:
            out.append("## 巡检范围")
            out.append("")
            out.extend(scope)
            out.append("")

        out.append("## 设备原始输出")
        out.append("")

        devices = sorted(task.devices.values(),
                         key=lambda d: (d.region or "", d.asset_name or "", d.asset_id or ""))
        for d in devices:
            _render_one_device(out, d)

    out.append("---")
    out.append(f"_Generated by Network Agent — {datetime.now(timezone.utc).isoformat()}_")
    return "\n".join(out)


def _render_one_device(out: list[str], d) -> None:
    """Append a single device's raw output to the Markdown lines."""
    header = f"### {d.asset_name or d.asset_id} ({d.host})"
    if d.region:
        header += f" — {d.region}"
    out.append(header)
    out.append("")
    out.append(f"- 厂商: `{d.vendor}`  类型: `{d.type}`  协议: `{d.protocol}`  状态: `{d.status}`")
    out.append(f"- 资产ID: `{d.asset_id}`")
    if d.errors:
        out.append("- **错误**: " + " · ".join(d.errors[:5]))
    out.append("")

    if not d.command_results:
        out.append("_(无命令输出)_")
        out.append("")
        return

    for cr in d.command_results:
        cmd_label = "批量巡检" if cr.command == "batch" else (cr.command or cr.check_id)
        if cr.ok:
            out.append(f"**{cmd_label}** ✓ ({cr.elapsed_ms}ms)")
        else:
            out.append(f"**{cmd_label}** ✗ {cr.error[:100] if cr.error else ''}")

        if cr.output_snippet:
            snippet = cr.output_snippet
            MAX_SNIPPET = 30000
            if len(snippet) > MAX_SNIPPET:
                suffix = f"\n... (截断，完整输出见 artifact {cr.artifact_id})"
                snippet = snippet[:MAX_SNIPPET] + suffix
            out.append("")
            out.append("```")
            out.append(snippet.rstrip())
            out.append("```")
        elif cr.artifact_id and not cr.ok:
            out.append(f"_(错误，无输出)_")
        out.append("")


def render_scope(task: InspectionTask) -> list[str]:
    lines: list[str] = []
    s = task.scope
    if s.region:
        lines.append(f"- 区域: {s.region}")
    if s.location:
        lines.append(f"- 位置: {s.location}")
    if s.type:
        lines.append(f"- 设备类型: {s.type}")
    if s.vendor:
        lines.append(f"- 厂商: {s.vendor}")
    if s.asset_ids:
        lines.append(f"- 指定设备: {', '.join(s.asset_ids)}")
    if s.tags:
        lines.append(f"- 标签: {', '.join(s.tags)}")
    lines.append(f"- 并发数: {task.max_concurrency}")
    return lines


def render_html(task: InspectionTask) -> str:
    """Standalone HTML report (v4.0: raw output + device cards)."""
    from html import escape

    status = escape(task.status or "")
    device_rows: list[str] = []

    for d in sorted(task.devices.values(),
                    key=lambda x: (x.region or "", x.asset_name or "", x.asset_id or "")):
        outputs = "<br><br>".join(
            f"<b>{escape(cr.command or cr.check_id)}</b> "
            f"{'✓' if cr.ok else '✗'}"
            + (f"<br><pre style='max-height:300px;overflow:auto;font-size:11px'>"
               f"{escape(cr.output_snippet[:3000])}</pre>"
               if cr.output_snippet else "")
            for cr in d.command_results
        ) or "—"

        device_rows.append(
            "<tr>"
            f"<td>{escape(d.asset_name or d.asset_id)}</td>"
            f"<td>{escape(d.host or '')}</td>"
            f"<td>{escape(d.region or '')}</td>"
            f"<td>{escape(d.vendor or '')}</td>"
            f"<td><span class='status {escape(d.status)}'>{escape(d.status)}</span></td>"
            f"<td>{outputs}</td>"
            "</tr>"
        )

    return f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>巡检报告 {escape(task.task_id)}</title>
<style>
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0;color:#172033;background:#f5f7fb}}
main{{max-width:1200px;margin:0 auto;padding:28px}}
h1{{margin:0 0 6px;font-size:26px}}
.muted{{color:#64748b}}
.summary{{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:18px 0}}
.card{{background:#fff;border:1px solid #dbe3ef;border-radius:8px;padding:14px}}
.num{{font-size:24px;font-weight:750}}
table{{width:100%;border-collapse:collapse;background:#fff;border:1px solid #dbe3ef;border-radius:8px;overflow:hidden}}
th,td{{padding:10px 12px;border-bottom:1px solid #e8eef6;text-align:left;vertical-align:top;font-size:13px}}
th{{background:#f8fafc;color:#475569;font-size:12px}}
.succeeded{{background:#dbeafe;color:#1d4ed8;padding:2px 8px;border-radius:99px;font-size:12px}}
.failed{{background:#fee2e2;color:#b91c1c;padding:2px 8px;border-radius:99px;font-size:12px}}
.partial{{background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:99px;font-size:12px}}
.skipped,.pending{{background:#e2e8f0;color:#475569;padding:2px 8px;border-radius:99px;font-size:12px}}
pre{{background:#f8fafc;border:1px solid #e8eef6;border-radius:6px;padding:10px;white-space:pre-wrap;word-break:break-word}}
</style>
</head>
<body>
<main>
<h1>巡检报告</h1>
<p class="muted">{escape(task.task_id)} · {escape(task.started_at or '—')} → {escape(task.finished_at or '—')} · {status}</p>
<div class="summary">
<div class="card"><span class="muted">总设备</span><div class="num">{task.total_assets}</div></div>
<div class="card"><span class="muted">成功</span><div class="num">{task.succeeded}</div></div>
<div class="card"><span class="muted">失败</span><div class="num">{task.failed}</div></div>
<div class="card"><span class="muted">部分</span><div class="num">{task.partial}</div></div>
<div class="card"><span class="muted">跳过</span><div class="num">{task.skipped}</div></div>
</div>
<h2>设备明细</h2>
<table>
<thead><tr><th>设备</th><th>地址</th><th>区域</th><th>厂商</th><th>状态</th><th>命令输出</th></tr></thead>
<tbody>{''.join(device_rows) or '<tr><td colspan="6">无</td></tr>'}</tbody>
</table>
</main>
</body>
</html>"""
