"""agent.modules.inspection.report

Markdown report generator. Pure function: takes an InspectionTask
and renders a structured Markdown summary. Used by both the API
endpoint (``GET /api/inspection/tasks/<id>/report``) and the
frontend Markdown download.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Iterable

from .models import (
    InspectionTask,
    Severity,
)


_SEV_ORDER: dict[str, int] = {"critical": 0, "warning": 1, "info": 2}


def render_markdown(task: InspectionTask) -> str:
    """Render the inspection task as a Markdown document."""
    out: list[str] = []
    out.append("# 巡检报告")
    out.append("")
    out.append(f"- **工作区**: {task.workspace_id}")
    out.append(f"- **巡检模板**: {task.profile_id} ({task.profile_display_name or ''})")
    out.append(f"- **开始时间**: {task.started_at or '—'}")
    out.append(f"- **结束时间**: {task.finished_at or '—'}")
    out.append(f"- **状态**: {task.status}")
    out.append("")
    out.append("## 巡检范围")
    out.append("")
    out.extend(_render_scope(task))
    out.append("")
    out.append("## 总体")
    out.append("")
    out.append(f"- 总设备数: **{task.total_assets}**")
    out.append(f"- 成功: **{task.succeeded}**")
    out.append(f"- 失败: **{task.failed}**")
    out.append(f"- 跳过: **{task.skipped}**")
    out.append(f"- critical: **{task.criticals}**")
    out.append(f"- warning: **{task.warnings}**")
    out.append(f"- info: **{task.infos}**")
    out.append("")
    out.append("## 关键发现")
    out.append("")
    if not any(d.findings for d in task.devices.values()):
        out.append("无")
    else:
        all_findings = sorted(
            (f for d in task.devices.values() for f in d.findings),
            key=lambda f: (_SEV_ORDER.get(f.severity, 99), f.title),
        )
        for f in all_findings:
            out.append(f"- `[{f.severity}]` {f.title}")
            if f.detail:
                out.append(f"  - {f.detail}")
            owner = task.devices.get(f.asset_id)
            if owner is not None:
                out.append(f"  - 设备: `{owner.asset_name or owner.asset_id}` ({owner.host})")
            if f.evidence:
                snippet = f.evidence.strip().splitlines()
                if snippet:
                    head = snippet[0][:120]
                    out.append(f"  - evidence: `{head}`")
    out.append("")
    out.append("## 设备明细")
    out.append("")
    for d in sorted(task.devices.values(), key=lambda x: (x.region, x.asset_name)):
        out.append(f"### {d.asset_name or d.asset_id} ({d.host})")
        out.append("")
        out.append(f"- 厂商: `{d.vendor}`  类型: `{d.type}`  协议: `{d.protocol}`")
        out.append(f"- 区域: `{d.region}`  位置: `{d.location}`")
        out.append(f"- 状态: `{d.status}`  supported={d.supported} limited_support={d.limited_support}")
        if d.errors:
            out.append("")
            out.append("**错误**:")
            for e in d.errors:
                out.append(f"  - {e}")
        if d.command_results:
            out.append("")
            out.append("**执行的检查**:")
            for cr in d.command_results:
                line = f"  - `{cr.check_id}` [{cr.category}] {cr.command_key}"
                line += " ✓" if cr.ok else f" ✗ {cr.error[:120] if cr.error else ''}"
                line += f"  ({cr.elapsed_ms}ms)"
                out.append(line)
        out.append("")
    out.append("---")
    out.append("")
    out.append(
        f"_Generated by Network Agent · "
        f"{datetime.now(timezone.utc).isoformat()}_"
    )
    return "\n".join(out)


def _render_scope(task: InspectionTask) -> Iterable[str]:
    s = task.scope
    yield "- 资产 ID（显式）: " + (
        ", ".join(s.asset_ids) if s.asset_ids else "—"
    )
    yield f"- 区域: {s.region or '—'}"
    yield f"- 物理位置: {s.location or '—'}"
    yield f"- 设备类型: {s.type or '—'}"
    yield f"- 厂商: {s.vendor or '—'}"
    yield f"- 标签: {', '.join(s.tags) if s.tags else '—'}"
    yield f"- 并发: {task.max_concurrency}"
