# agent/verifier.py
"""Output verifier — checks translate results meet baseline requirements."""

from agent.state import NetworkAgentState


def verify(state: NetworkAgentState) -> NetworkAgentState:
    """Verify the last skill result meets expectations."""
    sr = state.skill_results or state.tool_results
    if not sr:
        state.verification = {"status": "no_results"}
        return state

    result = sr if isinstance(sr, dict) else (sr[-1] if isinstance(sr, list) and sr else {})
    checks = {}

    # Structural checks
    checks["has_deployable_config"] = "deployable_config" in result
    checks["has_manual_review"] = "manual_review" in result
    checks["has_unsupported"] = "unsupported" in result
    checks["has_audit"] = "audit" in result

    # Red-line checks
    checks["no_full_output"] = "full_output" not in result
    checks["translator_entry_correct"] = result.get("translator_entry") == "translate_bundle"
    checks["no_llm_deployable"] = _check_no_llm_deployable(result)

    # Overall
    all_pass = all(checks.values())
    checks["status"] = "pass" if all_pass else "fail"

    state.verification = checks
    if not all_pass:
        failed = [k for k, v in checks.items() if not v and k != "status"]
        state.error = f"Verification failed: {', '.join(failed)}"

    return state


def _check_no_llm_deployable(result: dict) -> bool:
    """Ensure deployable_config was not generated by LLM."""
    # translate_bundle produces deterministic output; LLM would produce different markers
    return result.get("translator_entry") == "translate_bundle"
